//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.1-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.09.30 at 07:26:26 PM BST 
//


package uk.ac.rdg.resc.ncwms.config;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the uk.ac.rdg.resc.ncwms.config package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: uk.ac.rdg.resc.ncwms.config
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link NcWMS.Datasets }
     * 
     */
    public NcWMS.Datasets createNcWMSDatasets() {
        return new NcWMS.Datasets();
    }

    /**
     * Create an instance of {@link NcWMS.Service }
     * 
     */
    public NcWMS.Service createNcWMSService() {
        return new NcWMS.Service();
    }

    /**
     * Create an instance of {@link NcWMS.Datasets.Dataset }
     * 
     */
    public NcWMS.Datasets.Dataset createNcWMSDatasetsDataset() {
        return new NcWMS.Datasets.Dataset();
    }

    /**
     * Create an instance of {@link NcWMS }
     * 
     */
    public NcWMS createNcWMS() {
        return new NcWMS();
    }

}
