<%@page contentType="text/xml"%><%--application/vnd.google-earth.kml+xml"--%><%@page pageEncoding="UTF-8"%><?xml version="1.0" encoding="UTF-8"?>
<%@taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@taglib uri="/WEB-INF/taglib/wms2kml" prefix="wms2kml"%>
<%-- Creates the top-level KML to wrap the WMS

     Arguments passed in to this JSP:
     title: (String) Title for this KML document
     description: (String) description
     layers: (List<Layer>) Layers to include in this KML
     wmsBaseUrl: (String) URL to use as a base for future requests back to this server --%>
<kml xmlns="http://earth.google.com/kml/2.2"
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:schemaLocation="http://earth.google.com/kml/2.2 http://code.google.com/apis/kml/schema/kml22beta.xsd">
    <Document>
        <name>${title}</name>
        <description>${description}</description><%-- Generated by...  Contact details... --%>
        <c:forEach var="layer" items="${layers}">
            <wms2kml:displayableLayer layer="${layer}" baseURL="${wmsBaseUrl}"/>
        </c:forEach>
    </Document>
</kml>